### PR TITLE
Using LooseVersion to be compatible with pytest versioning

### LINKED ISSUE #39: pytest-remotedata is not compatible with dev versioning of pytest
The pytest version number for the developer branch is not compatible with `StrictVersion`, and thus I run into tons of errors like the one below when tried to use pytest dev with astropy core. 

I don't see a reason of why `StrictVersion` is preferred instead of `LooseVersion`. If there is something I miss @drdavella  please let me know.

```
____________________________________________________ ERROR at setup of test_numpy_types[c5] _____________________________________________________

item = <Function test_numpy_types[c5]>

    def pytest_runtest_setup(item):
    
>       if StrictVersion(pytest.__version__) < StrictVersion("3.6"):

/usr/local/lib/python3.7/site-packages/pytest_remotedata/plugin.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py:40: in __init__
    self.parse(vstring)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'StrictVersion' object has no attribute 'version'") raised in repr()] StrictVersion object at 0x13a052c88>
vstring = '5.0.1.dev15+g5d8da88e9.d20190702'

    def parse (self, vstring):
        match = self.version_re.match(vstring)
        if not match:
>           raise ValueError("invalid version number '%s'" % vstring)
E           ValueError: invalid version number '5.0.1.dev15+g5d8da88e9.d20190702'

/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py:137: ValueError
```

### PR DESCRIPTION
**Pull request by bsipocz**
This is to fix #39 

This can/should be backported to the 0.3.x branch in case we plan to have another release from there.

### CODE REVIEW

**Comment by bsipocz** [comment]
I'm not sure I understand how the numpy 3.5 windows build starts to require python2.7 packages 😥

**Comment by bsipocz** [comment]
@astrofrog - FYI: I had to restart the travis jobs several times as they are fluky with url timeouts, so if we suddenly find ourselves bored and have nothing to do, maybe we can look into making those tests more stable.

**Comment by dstansby** [comment]
Did this ever make it into a realease? I think we're running into errors like the following with sunpy tests, that would be solved with this PR (I think):
```
2020-07-13T15:52:03.5347368Z [gw3] linux -- Python 3.8.3 /home/vsts/work/1/s/.tox/py38-conda/bin/python
2020-07-13T15:52:03.5347725Z 
2020-07-13T15:52:03.5347972Z item = <Function test_lfu_cache>
2020-07-13T15:52:03.5348197Z 
2020-07-13T15:52:03.5348515Z     def pytest_runtest_setup(item):
2020-07-13T15:52:03.5348786Z     
2020-07-13T15:52:03.5349168Z >       if StrictVersion(pytest.__version__) < StrictVersion("3.6"):
2020-07-13T15:52:03.5349544Z 
2020-07-13T15:52:03.5350229Z ../../.tox/py38-conda/lib/python3.8/site-packages/pytest_remotedata/plugin.py:65: 
2020-07-13T15:52:03.5350897Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2020-07-13T15:52:03.5351642Z ../../.tox/py38-conda/lib/python3.8/distutils/version.py:40: in __init__
2020-07-13T15:52:03.5352083Z     self.parse(vstring)
2020-07-13T15:52:03.5352562Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2020-07-13T15:52:03.5353062Z 
2020-07-13T15:52:03.5353729Z self = <[AttributeError("'StrictVersion' object has no attribute 'version'") raised in repr()] StrictVersion object at 0x7f594c70f0a0>, vstring = '6.0.0rc1'
2020-07-13T15:52:03.5354144Z 
2020-07-13T15:52:03.5354453Z     def parse (self, vstring):
2020-07-13T15:52:03.5354779Z         match = self.version_re.match(vstring)
2020-07-13T15:52:03.5355134Z         if not match:
2020-07-13T15:52:03.5355646Z >           raise ValueError("invalid version number '%s'" % vstring)
2020-07-13T15:52:03.5356264Z E           ValueError: invalid version number '6.0.0rc1'
2020-07-13T15:52:03.5356562Z 
2020-07-13T15:52:03.5357049Z ../../.tox/py38-conda/lib/python3.8/distutils/version.py:137: ValueError
```

**Comment by hroncok** [comment]
> Did this ever make it into a release?

No. We have the same problems in Fedora.

**Pull request merged**
